apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nominatim.fullname" . }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nominatim.selectorLabels" . | nindent 6 }}

  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- with .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
        {{- include "nominatim.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nominatim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          workingDir: /nominatim
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.nominatim.extraEnv }}
            {{- include "common.tplvalues.render" (dict "value" .Values.nominatim.extraEnv "context" $) | nindent 12 }}
            {{- end }}
            - name: NOMINATIM_DATABASE_DSN
              value: {{ include "nominatim.databaseUrl" . }}
            - name: NOMINATIM_DATABASE_MODULE_PATH
              value: {{ .Values.nominatim.databaseModulePath }}
            - name: NOMINATIM_REPLICATION_URL
              value: {{ .Values.nominatimReplications.replicationUrl }}
            - name: NOMINATIM_FLATNODE_FILE
              value: /nominatim/flatnode.file
          command:
            - /bin/bash
            - -ec
            - |
                nominatim refresh --website
                {{- if and .Values.nominatimUi.enabled .Values.nominatimUi.install }}
                a2enmod rewrite
                {{- end }}
                /usr/sbin/apache2ctl -D FOREGROUND
          ports:
            - name: http
              containerPort: {{ include "nominatim.containerPort" . }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            {{- if .Values.projectDir.enabled }}
            - mountPath: /nominatim
              name: project-dir
            {{- end }}
            {{- if .Values.nominatimUi.enabled }}
            - mountPath: /etc/apache2/sites-available
              name: apache-config
            {{- if .Values.nominatimUi.install }}
            - mountPath: /nominatim-ui
              name: nominatim-ui
            {{- end }}
            {{- if .Values.nominatimUi.configuration }}
            - name: ui-config
              mountPath: /nominatim-ui/dist/theme/config.theme.js
              subPath: config.theme.js
            {{- end }}
            {{- end }}
      {{- if or .Values.nominatimInitialize.enabled .Values.nominatimUi.enabled }}
      initContainers:
      {{- if .Values.nominatimInitialize.enabled }}
        - name: init-wait
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          workingDir: /nominatim
          command:
          - /bin/bash
          - -ec
          - |
            until test -f /nominatim/.import-complete
            do
              echo "Waiting for init to complete"
              sleep 30
            done
          env:
            - name: PGHOST
              value: {{ include "nominatim.databaseHost" . }}
            - name: PGUSER
              value: {{ include "nominatim.databaseRoot" . }}
            - name: PGPASSWORD
              value: {{ include "nominatim.databaseRootPassword" . }}
            - name: PGDATABASE
              value: {{ include "nominatim.databaseName" . }}
          securityContext:
            {{- toYaml .Values.initSecurityContext | nindent 12 }}
          {{- with .Values.initResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.projectDir.enabled }}
            - mountPath: /nominatim
              name: project-dir
            {{- end }}
      {{- end }}
      {{- if and .Values.nominatimUi.enabled .Values.nominatimUi.install }}
        - name: nominatim-ui-download
          image: curlimages/curl
          workingDir: /nominatim-ui
          command:
          - /bin/sh
          - -ec
          - |
            curl -L {{ include "nominatim.uiUrl" . }} | tar -xz --strip-components 1
          securityContext:
            {{- toYaml .Values.initSecurityContext | nindent 12 }}
          volumeMounts:
          - mountPath: /nominatim-ui
            name: nominatim-ui
          {{- with .Values.initResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if  .Values.projectDir.enabled }}
        - name: project-dir
          persistentVolumeClaim:
            claimName: {{ .Values.projectDir.existingClaim | default (include "nominatim.fullname" .) }}
        {{- end }}
        - name: dshm
          emptyDir:
            medium: Memory
        - name: apache-config
          configMap:
            name: {{ include "nominatim.fullname" . }}-apache-configmap
      {{- if .Values.nominatimUi.enabled }}
        {{- if .Values.nominatimUi.configuration }}
        - name: ui-config
          configMap:
            name: {{ include "nominatim.fullname" . }}-ui-configmap
        {{- end }}
        {{- if .Values.nominatimUi.install }}
        - name: nominatim-ui
          emptyDir: {}
        {{- end }}
      {{- end }}
