{{- if and .Values.projectDir.enabled (not .Values.projectDir.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nominatim.fullname" . }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.projectDir.accessModes }}
    - {{ . | quote }}
      {{- end }}
  resources:
    requests:
      storage: {{ .Values.projectDir.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.projectDir "global" .Values.global) | nindent 2 }}
{{- end}}
