{{- if .Values.nominatimUi.configuration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nominatim.fullname" . }}-ui-configmap
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
data:
  config.theme.js: |-
    {{ .Values.nominatimUi.configuration | nindent 4 }}
{{- end -}}
